Update installation instruction for global use
Edu4rdSHL/unimap pull request #8
Opened 2022-04-14 18:17 UTC by rudSarkar

Updated the installation for global use by a normal user of the machine, because pre-built binary from the releases causes error while running unimap.

If the user compiled and follow the instruction they can use just type the command `$ unimap`.

2022-04-14 20:02 UTC, Edu4rdSHL commented
>  because pre-built binary from the releases causes error while running unimap.

Can you tell me what is the error?

2022-04-14 20:30 UTC, rudSarkar commented on README.md
> +3. cp ./target/release/unimap /usr/local/bin
this command will copy the unimap binary to bin directory for global use.

2022-04-14 20:32 UTC, rudSarkar commented
Downloaded this binary [unimap-linux](https://github.com/Edu4rdSHL/unimap/releases/download/0.5.1/unimap-linux) When I run this it returns an error like below:

```
rudra@workspace:~$ ./unimap-linux -t example.com

[INFO] Performing parallel resolution for 1 targets with 1 threads, it will take a while...

[ERROR] Error waiting command to finish for 1xx.1x.2x.2xx, continuing with remaining hosts. Description: No such file or directory (os error 2)+------------+---------------+------------+----------+
|    HOST    |      IP       | OPEN PORTS | SERVICES |
+============+===============+============+==========+
| chorki.com | 1xx.1x.2x.2xx | NULL       | ++       |
|            |               |            | ++       |
+------------+---------------+------------+----------+
```

As it's not working then the user has to compile the binary and here I just added a line in README for globally using the binary comment added you can check from there.

2022-04-14 20:46 UTC, Edu4rdSHL commented
That error is normal, it happens when Nmap doesn't return a file for the scanned host. I see that you're running Nmap as a normal user and of course, that will not work. As explained [in the docs](https://github.com/Edu4rdSHL/unimap#usage):

> Unimap requires root/administrator privileges to launch [Nmap TCP SYN (Stealth) Scan](https://nmap.org/book/synscan.html), we use it for accuracy and performance reasons. If you are on Linux or Linux-based, just use a root shell or run the tool with sudo, in Windows you can open a Command Prompt (CMD) as Administrator and run the tool as usual.

So, just run is as root.

2022-04-14 20:47 UTC, Edu4rdSHL requested changes

2022-04-14 20:47 UTC, Edu4rdSHL commented on README.md
> +# copy the unimap binaries for run from everywhere
```suggestion
# Now you can use the `unimap` command from everyewhere.
```

2022-04-14 20:53 UTC, rudSarkar commented
> That error is normal, it happens when Nmap doesn't return a file for the scanned host. I see that you're running Nmap as a normal user and of course, that will not work. As explained [in the docs](https://github.com/Edu4rdSHL/unimap#usage):
> 
> > Unimap requires root/administrator privileges to launch [Nmap TCP SYN (Stealth) Scan](https://nmap.org/book/synscan.html), we use it for accuracy and performance reasons. If you are on Linux or Linux-based, just use a root shell or run the tool with sudo, in Windows you can open a Command Prompt (CMD) as Administrator and run the tool as usual.
> 
> So, just run is as root.

My bad I forget to use root user thanks.

2022-04-14 20:55 UTC, Edu4rdSHL commented
I don't think that it's necessary unless we clarify that it's for Linux-based systems. Unimap can run on Windows, Linux, Mac, and almost any other OS that doesn't have `/usr/local/bin`, please clarify that this step is only for Linux-based OSes.

2022-04-15 05:02 UTC, rudSarkar commented
> I don't think that it's necessary unless we clarify that it's for Linux-based systems. Unimap can run on Windows, Linux, Mac, and almost any other OS that doesn't have `/usr/local/bin`, please clarify that this step is only for Linux-based OSes.

For Windows user they can just set a environment path to run globally.

2022-04-15 05:43 UTC, rudSarkar commented
> Downloaded this binary [unimap-linux](https://github.com/Edu4rdSHL/unimap/releases/download/0.5.1/unimap-linux) When I run this it returns an error like below:
> 
> ```
> rudra@workspace:~$ ./unimap-linux -t example.com
> 
> [INFO] Performing parallel resolution for 1 targets with 1 threads, it will take a while...
> 
> [ERROR] Error waiting command to finish for 1xx.1x.2x.2xx, continuing with remaining hosts. Description: No such file or directory (os error 2)+------------+---------------+------------+----------+
> |    HOST    |      IP       | OPEN PORTS | SERVICES |
> +============+===============+============+==========+
> | chorki.com | 1xx.1x.2x.2xx | NULL       | ++       |
> |            |               |            | ++       |
> +------------+---------------+------------+----------+
> ```
> 
> As it's not working then the user has to compile the binary and here I just added a line in README for globally using the binary comment added you can check from there.

So, basically, I find out that this error occurred only on the Google Cloud shell even with the root permission but works on the digital ocean cloud shell or other VPS as well.

2022-04-15 08:22 UTC, Edu4rdSHL commented
> So, basically, I find out that this error occurred only on the Google Cloud shell even with the root permission but works on the digital ocean cloud shell or other VPS as well.

Weird, are you sure that Nmap is installed on the Google Cloud VM? I tested it and it works just fine.

Thanks for the PR, btw.

2022-04-15 08:23 UTC, merged

2022-04-15 08:31 UTC, rudSarkar commented
> > So, basically, I find out that this error occurred only on the Google Cloud shell even with the root permission but works on the digital ocean cloud shell or other VPS as well.
> 
> Weird, are you sure that Nmap is installed on the Google Cloud VM? I tested it and it works just fine.
> 
> Thanks for the PR, btw.

Yeah, I have installed Nmap but faced the same issue. Maybe I gotta reset it and thanks for the merge